name: Bump version by tag

on:
  push:
    tags:
      - patch
      - minor
      - major

jobs:
  bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Read current version
      id: read
      run: |
        version=$(cat version.txt)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Determine bump type
      id: tag
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "bump_type=$tag" >> $GITHUB_OUTPUT

    - name: Bump version
      id: bump
      run: |
        IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.read.outputs.version }}"
        case "${{ steps.tag.outputs.bump_type }}" in
          patch) PATCH=$((PATCH+1)) ;;
          minor) MINOR=$((MINOR+1)); PATCH=0 ;;
          major) MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0 ;;
        esac
        new="$MAJOR.$MINOR.$PATCH"
        echo "$new" > version.txt
        echo "new_version=$new" >> $GITHUB_OUTPUT

    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "chore: bump ${{ steps.tag.outputs.bump_type }} → ${{ steps.bump.outputs.new_version }}"
        git push origin HEAD
